In [1]:
# %%bash 
# pip3 -q install gym
# pip3 -q install pyglet
# pip3 -q install pyopengl
# pip3 -q install pyvirtualdisplay

You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [50]:
import gym

env = gym.make('CartPole-v0')
print('observation space:', env.observation_space)
print('action space:', env.action_space)

obs = env.reset()
#env.render()
print('initial observation:', obs)

action = env.action_space.sample()
obs, r, done, info = env.step(action)
print('next observation:', obs)
print('reward:', r)
print('done:', done)
print('info:', info)
print(env.observation_space.high)
print(env.observation_space.low)


from gym import envs
# print(envs.registry.all())

observation space: Box(4,)
action space: Discrete(2)
initial observation: [-0.01728797 -0.03825185 -0.00374553  0.00913405]
next observation: [-0.01805301  0.15692362 -0.00356285 -0.28472828]
reward: 1.0
done: False
info: {}
[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [2]:
import gym 

frames = []
# for i in range(3):
#     obs = env.reset()
#     done = False
#     R = 0
#     t = 0
#     while not done and t < 200:
#         frames.append(env.render(mode = 'rgb_array'))
#         # define formula for action and put that is step
#         #  action = agent.act(obs)
#         obs, r, done, _ = env.step(env.action_space.sample())
#         R += r
#         t += 1
#     print('test episode:', i, 'R:', R)
#     # agent.stop_episode()
# env.render()


for _ in range(100):
    frames.append(env.render(mode = 'rgb_array'))
    env.step(env.action_space.sample()) # take a random action
env.close()

# for inline plotting maybe
# import matplotlib.pyplot as plt
# import matplotlib.animation
# import numpy as np
# from IPython.display import HTML

# plt.figure(figsize=(frames[0].shape[1] / 72.0, frames[0].shape[0] / 72.0), dpi = 72)
# patch = plt.imshow(frames[0])
# plt.axis('off')
# animate = lambda i: patch.set_data(frames[i])
# ani = matplotlib.animation.FuncAnimation(plt.gcf(), animate, frames=len(frames), interval = 50)
# HTML(ani.to_jshtml())

/usr/local/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [51]:
import gym
frames = [] 
env = gym.make('CartPole-v0')
for episode in range(20):
    observation = env.reset()
    for t in range(100):
        frames.append(env.render(mode = 'rgb_array'))
        # print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

Episode finished after 15 timesteps
Episode finished after 12 timesteps
Episode finished after 25 timesteps
Episode finished after 11 timesteps
Episode finished after 13 timesteps
Episode finished after 18 timesteps
Episode finished after 16 timesteps
Episode finished after 14 timesteps
Episode finished after 21 timesteps
Episode finished after 15 timesteps
Episode finished after 13 timesteps
Episode finished after 32 timesteps
Episode finished after 16 timesteps
Episode finished after 14 timesteps
Episode finished after 39 timesteps
Episode finished after 11 timesteps
Episode finished after 21 timesteps
Episode finished after 27 timesteps
Episode finished after 15 timesteps
Episode finished after 31 timesteps


In [65]:
import numpy as np
# apply manual Q-learning https://www.oreilly.com/radar/introduction-to-reinforcement-learning-and-openai-gym/
Q = np.zeros([env.observation_space.shape[0], env.action_space.n])
print(Q)
G = 0
alpha = 0.618
for episode in range(1,1001):
    frames.append(env.render(mode = 'rgb_array'))
    done = False
    G, reward = 0,0
    state = env.reset() # creates a random state
    i = 0
    for s in state:
        Q[i,0] = s
        i +=1 
    # print(Q.shape)    
    while done != True:
        action = np.argmax(Q[:1]) #1
        state2, reward, done, info = env.step(action) #2
        i = 0
        for s in state:
            Q[i,0] += alpha * (reward + np.max(state2[i]) - Q[i,0])
            Q[i,1] += alpha * (reward + np.max(state2[i]) - Q[i,1])
            i +=1 
        # Q[state,action]  #3
        G += reward
        state = state2 
    # print(Q.shape)      
    if episode % 50 == 0:
        print('Episode {} Total Reward: {}'.format(episode,G))
        



[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Episode 50 Total Reward: 11.0
Episode 100 Total Reward: 9.0
Episode 150 Total Reward: 8.0
Episode 200 Total Reward: 9.0
Episode 250 Total Reward: 10.0
Episode 300 Total Reward: 10.0
Episode 350 Total Reward: 9.0
Episode 400 Total Reward: 10.0
Episode 450 Total Reward: 9.0
Episode 500 Total Reward: 9.0
Episode 550 Total Reward: 10.0
Episode 600 Total Reward: 9.0
Episode 650 Total Reward: 11.0
Episode 700 Total Reward: 10.0
Episode 750 Total Reward: 10.0
Episode 800 Total Reward: 9.0
Episode 850 Total Reward: 9.0
Episode 900 Total Reward: 9.0
Episode 950 Total Reward: 9.0
Episode 1000 Total Reward: 9.0
