In [1]:
# %%bash 
# pip3 -q install gym
# pip3 -q install pyglet
# pip3 -q install pyopengl
# pip3 -q install pyvirtualdisplay

You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [1]:
import gym

env = gym.make('CartPole-v0')
print('observation space:', env.observation_space)
print('action space:', env.action_space)

obs = env.reset()
#env.render()
print('initial observation:', obs)

action = env.action_space.sample()
obs, r, done, info = env.step(action)
print('next observation:', obs)
print('reward:', r)
print('done:', done)
print('info:', info)


observation space: Box(4,)
action space: Discrete(2)
initial observation: [0.03786961 0.04007578 0.00286162 0.03029388]
next observation: [ 0.03867112 -0.15508709  0.0034675   0.32387831]
reward: 1.0
done: False
info: {}


In [2]:
frames = []
# for i in range(3):
#     obs = env.reset()
#     done = False
#     R = 0
#     t = 0
#     while not done and t < 200:
#         frames.append(env.render(mode = 'rgb_array'))
#         # define formula for action and put that is step
#         #  action = agent.act(obs)
#         obs, r, done, _ = env.step(env.action_space.sample())
#         R += r
#         t += 1
#     print('test episode:', i, 'R:', R)
#     # agent.stop_episode()
# env.render()


for _ in range(100):
    frames.append(env.render(mode = 'rgb_array'))
    env.step(env.action_space.sample()) # take a random action
env.close()

# for inline plotting maybe
# import matplotlib.pyplot as plt
# import matplotlib.animation
# import numpy as np
# from IPython.display import HTML

# plt.figure(figsize=(frames[0].shape[1] / 72.0, frames[0].shape[0] / 72.0), dpi = 72)
# patch = plt.imshow(frames[0])
# plt.axis('off')
# animate = lambda i: patch.set_data(frames[i])
# ani = matplotlib.animation.FuncAnimation(plt.gcf(), animate, frames=len(frames), interval = 50)
# HTML(ani.to_jshtml())

/usr/local/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [3]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        frames.append(env.render(mode = 'rgb_array'))
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

979193  0.01658002  0.50907254]
[ 0.00327099 -0.5351435   0.02676147  0.80693392]
[-0.00743188 -0.34039836  0.04290015  0.52278776]
[-0.01423985 -0.53609704  0.0533559   0.82867446]
[-0.02496179 -0.34174356  0.06992939  0.5532383 ]
[-0.03179666 -0.14766969  0.08099416  0.28338149]
[-0.03475005  0.04620924  0.08666179  0.01730272]
[-0.03382587 -0.15004176  0.08700784  0.33602117]
[-0.0368267  -0.34628723  0.09372827  0.65482389]
[-0.04375245 -0.15258662  0.10682474  0.39306406]
[-0.04680418  0.04087009  0.11468603  0.13587993]
[-0.04598678 -0.15569184  0.11740362  0.46242976]
[-0.04910061 -0.35226032  0.12665222  0.78969017]
[-0.05614582 -0.5488729   0.14244602  1.11938312]
[-0.06712328 -0.35587738  0.16483369  0.87455955]
[-0.07424083 -0.55281027  0.18232488  1.21419691]
[-0.08529703 -0.36044751  0.20660882  0.98374245]
Episode finished after 25 timesteps
[0.0139748  0.03921609 0.02433751 0.00022396]
[ 0.01475912 -0.15624629  0.02434199  0.30048523]
[0.01163419 0.0385204  0.03035169 0.